---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/pauloandrino/pluralsight-spring-cloudconfig-wa-tolls # default
          #username: abc
          #password: abc
          search-paths:
            - 'station*'
          repos:
             local:
                pattern: '*/local'
                uri: https://github.com/pauloandrino/pluralsight-spring-cloudconfig-wa-perf # alt
                search-paths:
                 - 'station*'
security:
  basic:
    enabled: true
  user:
    name: pluralsight
    password: pluralsight